root: .

structure:
  readme: ./README.md
  summary: ./SUMMARY.md

redirects:
  reference: Python_Client_3-x/introudction/about-the-fiddler-client.md
  changelog: release_notes/README.md
  releases: release_notes/README.md
  docs/databricks-integration: INTEGRATIONS/ml-platform-integrations/databricks-integration.md
  docs/task-types: Platform_Guide/task-types.md
  welcome: README.md
  docs: README.md
  architecture: Deployment_Guide/deploying-fiddler/system-architecture.md
  docs/system-architecture: Deployment_Guide/deploying-fiddler/system-architecture.md
  changelog/analytics-ui: release_notes/README.md
  docs/coherence-beta: Python_Client_3-x/api-methods-30.md
  docs/data-and-environments: Platform_Guide/product-concepts.md
  docs/faithfulness-beta: Python_Client_3-x/api-methods-30.md
  docs/llm: Platform_Guide/llm-monitoring/README.md
  docs/publishing-events-with-complex-data-formats: Client_Guide/publishing-production-data/README.md
  docs/regression-models: UI_Guide/evaluation-ui.md
  docs/custom-metrics: UI_Guide/monitoring-ui/custom-metrics.md
  docs/segments: UI_Guide/monitoring-ui/segments.md
  docs/quick-start: QuickStart_Notebooks/quick-start.md
  pages/user-guide/data-science-concepts/analytics: Platform_Guide/analytics-eval-platform.md
  pages/user-guide/data-science-concepts/explainability/point-explainability/: Platform_Guide/explainability/point-explainability-platform.md
  docs/uploading-a-baseline-dataset: Client_Guide/creating-a-baseline-dataset.md
  docs/designing-a-baseline-dataset: Client_Guide/creating-a-baseline-dataset.md
  docs/model-deployment: platform-guide/explainability/flexible-model-deployment/README.md
  page/python-client-version-history: python-client-history.md
  docs/data-integrity: Platform_Guide/monitoring-platform/data-integrity-platform.md
  reference/clientadd_alert_rule: Python_Client_3-x/api-methods-30.md
  platform-guide/explainability: product-guide/explainability/flexible-model-deployment/README.md
  platform-guide/explainability/flexible-model-deployment/on-prem-manual-flexible-model-deployment-xai: product-guide/explainability/flexible-model-deployment/on-prem-manual-flexible-model-deployment-xai.md
  platform-guide/platform-security: product-guide/platform-security.md
  platform-guide/supported-browsers: product-guide/supported-browsers.md
  platform-guide/administration-platform: product-guide/administration-platform.md
  platform-guide/llm-monitoring/embedding-visualization-with-umap: product-guide/llm-monitoring/embedding-visualization-with-umap.md
  platform-guide/llm-monitoring/selecting-enrichments: product-guide/llm-monitoring/selecting-enrichments.md
  platform-guide/llm-monitoring/llm-based-metrics: product-guide/llm-monitoring/llm-based-metrics.md
  platform-guide/llm-monitoring/README: product-guide/llm-monitoring/README.md
  platform-guide/llm-monitoring/enrichments-private-preview: product-guide/llm-monitoring/enrichments-private-preview.md
  platform-guide/product-concepts: product-guide/product-concepts.md
  platform-guide/task-types: product-guide/task-types.md
  platform-guide/analytics-eval-platform: product-guide/analytics-eval-platform.md
  platform-guide/explainability/flexible-model-deployment/manual-flexible-model-deployment: product-guide/explainability/flexible-model-deployment/manual-flexible-model-deployment.md
  platform-guide/explainability/global-explainability-platform: product-guide/explainability/global-explainability-platform.md
  platform-guide/explainability/point-explainability-platform: product-guide/explainability/point-explainability-platform.md
  platform-guide/explainability/README: product-guide/explainability/README.md
  platform-guide/explainability/artifacts-and-surrogates: product-guide/explainability/artifacts-and-surrogates.md
  platform-guide/explainability/global-explanations-platform: product-guide/explainability/global-explanations-platform.md
  platform-guide/explainability/point-explanations: product-guide/explainability/point-explanations.md
  platform-guide/integrity-constraints: product-guide/integrity-constraints.md
  platform-guide/handling-class-imbalance: product-guide/handling-class-imbalance.md
  platform-guide/monitoring-platform/dashboards-platform: product-guide/monitoring-platform/dashboards-platform.md
  platform-guide/monitoring-platform/model-versions: product-guide/monitoring-platform/model-versions.md
  platform-guide/monitoring-platform/traffic-platform: product-guide/monitoring-platform/traffic-platform.md
  platform-guide/monitoring-platform/custom-metrics: product-guide/monitoring-platform/custom-metrics.md
  platform-guide/monitoring-platform/alerts-platform: product-guide/monitoring-platform/alerts-platform.md
  platform-guide/monitoring-platform/performance-tracking-platform: product-guide/monitoring-platform/performance-tracking-platform.md
  platform-guide/monitoring-platform/statistics: product-guide/monitoring-platform/statistics.md
  platform-guide/monitoring-platform/README: product-guide/monitoring-platform/README.md
  platform-guide/monitoring-platform/vector-monitoring-platform: product-guide/monitoring-platform/vector-monitoring-platform.md
  platform-guide/monitoring-platform/class-imbalanced-data: product-guide/monitoring-platform/class-imbalanced-data.md
  platform-guide/monitoring-platform/data-integrity-platform: product-guide/monitoring-platform/data-integrity-platform.md
  platform-guide/monitoring-platform/data-drift-platform: product-guide/monitoring-platform/data-drift-platform.md
  platform-guide/monitoring-platform/fiddler-query-language: product-guide/monitoring-platform/fiddler-query-language.md
  platform-guide/monitoring-platform/segments: product-guide/monitoring-platform/segments.md
  platform-guide/monitoring-platform/monitoring-charts-platform: product-guide/monitoring-platform/monitoring-charts-platform.md
  platform-guide/monitoring-platform/embedding-visualization-with-umap-copy: product-guide/monitoring-platform/embedding-visualization-with-umap.md
  product-guide/monitoring-platform/embedding-visualization-with-umap-copy: product-guide/monitoring-platform/embedding-visualization-with-umap.md
  platform-guide/histogram-binning: product-guide/histogram-binning.md
  platform-guide/fairness: product-guide/fairness.md
  history/release_notes: release-notes/README.md
  introduction/about-the-fiddler-client: Python_Client_3-x/introudction/about-the-fiddler-client.md
