MD001: false # heading-increment
MD003: false # heading-style
MD004: false # ul-style
MD007: false # ul-indent
MD009: false # no-trailing-spaces
MD010: false # no-hard-tabs
MD012: false # no-multiple-blanks
MD013: false # line-length
MD022: false # blanks-around-headings
MD023: false # heading-start-left
MD024: false # no-duplicate-heading
MD025: false # single-title/single-h1
MD026: false # no-trailing-punctuation
MD028: false # no-blanks-blockquote
MD029: false # ol-prefix
MD030: false # list-marker-space
MD031: false # blanks-around-fences
MD032: false # blanks-around-lists
MD033: false # no-inline-html
MD034: false # no-bare-urls
MD036: false # no-emphasis-as-heading
MD037: false # no-space-in-emphasis
MD038: false # no-space-in-code
MD039: false # no-space-in-links
MD040: false # fenced-code-language
MD041: false # first-line-heading/first-line-h1
MD045: false # no-alt-text
MD046: false # code-block-style
MD047: false # single-trailing-newline
MD056: false # table-column-count
