name: Build and push Docker image to ECR

on:
  push:
    branches: [ "main", "cleanup-saif" ]
  workflow_dispatch:

permissions:
  id-token: write    # required for GitHub OIDC to AWS
  contents: read

env:
  AWS_REGION: us-west-2
  ECR_REGISTRY: 079310353266.dkr.ecr.us-west-2.amazonaws.com
  ECR_REPOSITORY: fiddler-chatbot
  IMAGE_TAG: latest
  ASSUME_ROLE: arn:aws:iam::079310353266:role/arc-github-actions-role

jobs:
  build-and-push:
    runs-on: ["fiddler-runners"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Option A: Configure AWS via GitHub OIDC (recommended)
      # Replace the role ARN below with your IAM role that trusts your GitHub org/repo.
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false